/*********************************************************************************
 * 
 * Ce fichier contient toutes les constantes nécessaires au fonctionnement du jeu.
 * En particulier les listes de mots et de phrases proposés à l'utilisateur
 * 
 *********************************************************************************/

// Déclaration des tableaux contenant les listes des mots proposés à l'utilisateur
const listeMots = [
    "Cachalot",
    "Pétunia",
    "Serviette",
    "Éléphant",
    "Télévision",
    "Ordinateur",
    "Téléphone",
    "Chien",
    "Chat",
    "Oiseau",
    "Arbre",
    "Maison",
    "Voiture",
    "Livre",
    "Table",
    "Chaise",
    "Fenêtre",
    "Porte",
    "Mur",
    "Plafond",
    "Sol",
    "Lampe",
    "Bureau",
    "Chapeau",
    "Lunettes",
    "Montre",
    "Stylo",
    "Crayon",
    "Papier",
    "Ciseaux",
    "Tasse",
    "Assiette",
    "Fourchette",
    "Couteau",
    "Cuillère",
    "Réfrigérateur",
    "Congélateur",
    "Four",
    "Micro-ondes",
    "Lave-vaisselle",
    "Lave-linge",
    "Sèche-linge",
    "Aspirateur",
    "Balai",
    "Serpillière",
    "Seau",
    "Éponge",
    "Savon",
    "Dentifrice",
    "Brosse à dents",
    "Rasoir",
    "Shampoing",
    "Après-shampoing",
    "Déodorant",
    "Parfum",
    "Lotion",
    "Crème",
    "Gel douche",
    "Peigne",
    "Brosse à cheveux",
    "Miroir",
    "Serviette de bain",
    "Gant de toilette",
    "Tapis de bain",
    "Rideau de douche",
    "Baignoire",
    "Douche",
    "Lavabo",
    "Toilettes",
    "Poubelle",
    "Recyclage",
    "Compost",
    "Jardin",
    "Pelouse",
    "Fleurs",
    "Arbustes",
    "Arrosoir",
    "Tonte",
    "Pelle",
    "Râteau",
    "Brouette",
    "Tuyau",
    "Piscine",
    "Barbecue",
    "Chaise longue",
    "Parasol",
    "Table de pique-nique",
    "Banc",
    "Balançoire",
    "Toboggan",
    "Sable",
    "Eau",
    "Soleil",
    "Lune",
    "Étoiles",
    "Nuages",
    "Pluie",
    "Neige",
    "Vent",
    "Tonnerre",
    "Éclair",
    "Arc-en-ciel"
];

const listePhrases = [
    "La vie, l'univers et le reste",
    "La réponse à la grande question sur la vie, l'univers et le reste est 42",
    "Pas de panique",
    "La Terre est une aire de repos hyperspatiale",
    "Le dauphin est un animal plus intelligent que l'homme",
    "Le thé est une boisson merveilleuse",
    "La serviette est l'objet le plus utile qu'un voyageur interstellaire puisse posséder",
    "Le guide du voyageur galactique a été écrit par Ford Prefect",
    "La Vogon Constructor Fleet a détruit la Terre",
    "Zaphod Beeblebrox est le président de la galaxie",
    "Marvin est un robot paranoïaque",
    "Le cœur en or est un vaisseau spatial volé par Zaphod",
    "Le restaurant du bout de l'univers sert des plats délicieux",
    "La planète Magrathea a été créée pour fabriquer des planètes sur mesure",
    "Slartibartfast est un spécialiste des fjords",
    "Les souris sont plus intelligentes que les humains",
    "Le point de vue de Sirius Cybernetics Corporation est que toute perte de vie humaine est regrettable",
    "La dématérialisation est une expérience désagréable",
    "Le guide du voyageur galactique est un ouvrage indispensable",
    "La poésie Vogon est la pire de l'univers",
    "Les portes de l'improbabilité infinie permettent de voyager instantanément dans l'espace et le temps",
    "Les Krikkits sont une race extraterrestre qui déteste la vie, l'univers et le reste",
    "Le Pot de fleurs totalement perspicace est un être vivant qui sait tout",
    "Le Bistromathique est un art martial qui permet de tuer en calculant",
    "Le Guide du voyageur galactique a été traduit en toutes les langues connues, y compris le langage baleinier",
    "Les baleines sont des créatures extrêmement intelligentes"
];